name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-2019

    steps:  
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 2.2.102
   
    - name: Restore dependencies
      run: dotnet restore src/PartsUnlimitedWebsite/PartsUnlimitedWebsite.csproj
      
    - name: Build
      run: dotnet build src/PartsUnlimitedWebsite/PartsUnlimitedWebsite.csproj --no-restore --configuration Release
      
    - name: Test
      run: dotnet test src/PartsUnlimitedWebsite/PartsUnlimitedWebsite.csproj --no-build --verbosity normal
